spring.application.name=leelify-api
server.port=8080

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/leelify_db?serverTimezone=Europe/Madrid}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=never
